### ISSUE TITLE
Magazine editor active tab not highlighted

### ISSUE THREAD

**Issue by Seanharrs** [Seanharrs/flipboard-dark#1]
The secondary column's active editor-tabs list item is showing as a brighter colour, it only works on hover.

Current behaviour is that the tab title and the image for the active tab both appear as the same colour as all the others:
![current](https://user-images.githubusercontent.com/13175844/42490624-bff0e970-8454-11e8-9aa9-6dd572839cfc.PNG)

Expected behaviour is that the tab title and the image for the active tab both appear as a brighter colour to signify which is currently selected:
![expected](https://user-images.githubusercontent.com/13175844/42490631-c70db738-8454-11e8-8cd5-90a4c83800c4.PNG)

Note, the expected behaviour image above is what shows on hover, I have been unable to get it to remain like that once the hover is lost. The :active and :focused and :visited selectors do not appear to help resolve this issue. I have already attempted the following:
```css
.editor-tabs .tab-title:active span { /* and .tab-title:focused and .tab-title:visited */
    color: #F7F7F7 !important;
}
.editor-tabs .tab-title span:active { /* and span:focused and span:active */
    color: #F7F7F7 !important;
}
.editor-tabs:active .tab-title span { /* and .editor-tabs:focused and .editor-tabs:active */
    color: #F7F7F7 !important;
}
```
There seems to be some javascript affecting the elements and changing their colour.
