### ISSUE TITLE
Magazine editor analytics graph null state text is black

### ISSUE THREAD

**Issue by Seanharrs** [Seanharrs/flipboard-dark#2]
The "No Activity" text in each of the analytics graphs when they're in a null state is black, when it should be styled to be a brighter colour so it is more visible against the background.

Current:
![current](https://user-images.githubusercontent.com/13175844/42490971-2876390e-8456-11e8-8017-b100fe1e7ba3.PNG)

Expected: The "No Activity" text should be brighter, most likely #DDD like almost all other text elements.

I have already attempted to style the text directly, with:
```css
.stats-dashboard .chart-null-state {
    color: #DDD !important;
    opacity: 1 !important;
}
```
The opacity was to ensure no parent element was changing its opacity and making it look darker, but I have since checked and found to parent element adjusting the opacity anyway. My Firefox browser shows that the element does indeed have the text color #DDD, but the text still appears black.
