### ISSUE TITLE
Some background-image underlines are too close

### ISSUE THREAD

**Issue by Seanharrs** [Seanharrs/flipboard-dark#6]
Some of the underlined elements on about.flipboard.com URLs have their underlines set too close to the text. 

For example, these appear identically with or without the theme enabled:
![acceptable](https://user-images.githubusercontent.com/13175844/42671616-3600e5e2-86a4-11e8-81fe-8cf7188b897a.PNG)
But these appear too close:
![tooclose](https://user-images.githubusercontent.com/13175844/42671617-3638e230-86a4-11e8-99a2-ea109d933438.PNG)

This can be resolved by moving them out to their own separate rules, with different pixel measurements for each corner of the linear-gradient. For example:
```css
a {
  background-image: linear-gradient(to top, rgba(0,0,0,0), rgba(0,0,0,0) 0px, #D22 0px, #D22 1px, rgba(0,0,0,0) 1px) !important;
  /* versus */
  background-image: linear-gradient(to top, rgba(0,0,0,0), rgba(0,0,0,0) 2px, #D22 2px, #D22 3px, rgba(0,0,0,0) 3px) !important;
}
```
The correct pixel values for each unique selector that is incorrect should be in Flipboard's CSS files.
